[package]
name = "sound"
version = "0.1.0"
edition = "2021"

[dependencies]
fundsp = "0.16.0"
cpal = "0.15.2"
assert_no_alloc = "1.1.2"
anyhow = "1.0.77"
funutd = "0.14.0"
rand = "0.8.5"
assert_approx_eq = "1.1.0"
